### ISSUE TITLE
Broken links in directory

### ISSUE THREAD

**Issue by samarjeet27** [fossasia/directory.api.fossasia.net#168]
The directory.json has some broken links which were merged earlier, as a result the build is failing
See - https://travis-ci.org/fossasia/directory.api.fossasia.net/jobs/47348148

what should we do about this ?

@andibraeu @mariobehling @RoonyH

**Comment by namangoel1** [comment]
@samarjeet27 I think it's simple, find who's to be **blame**d for those additions, remove the links, and ask them to add it back?

**Comment by samarjeet27** [comment]
@namangoel1 yeah, we can but some links like
 http://mm.fedoracommunity.org/FedoraProject-MyanmarCommunity-api.json

it was first online that's why the build passed ,but now it isn't

**Comment by samarjeet27** [comment]
https://github.com/fossasia/directory.api.fossasia.net/pull/169
Fixes everything except the fedora project link
should I remove it too ?

**Comment by orcakrilozona** [comment]
Hi there @samarjeet27 ,

Yeah, I recently moving the fedora myanmar site to own new VPS, and that was why the link was broken. I've restored it already.

**Comment by samarjeet27** [comment]
@orcakrilozona, 
I've reverted that commit, please add the link to the raw url from the fossasia-comunities repo.

Thanks !

**Comment by samarjeet27** [comment]
ok thanks @orcakrilozona 
travis is green after merging this https://github.com/fossasia/directory.api.fossasia.net/pull/169

**Comment by orcakrilozona** [comment]
Thank you too @samarjeet27 :D
